#!/bin/sh
# postinst script for kafka
# based on script for sensu: https://github.com/sensu/sensu-build/blob/master/pkg_scripts/deb/postinst


set -e

# summary of how this script can be called and ordering:
#  http://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
#  http://www.proulx.com/~bob/debian/hints/DpkgScriptOrder

create_kafka_user_group() {
    # create kafka group
    if ! getent group kafka >/dev/null; then
        groupadd -r kafka
    fi

    # create kafka user
    if ! getent passwd kafka >/dev/null; then
        useradd -r -g kafka -d /usr/local/kafka \
            -s /bin/false -c "Kafka service user" kafka
    fi
}

create_zookeeper_user_group() {
    # create kafka group
    if ! getent group zookeeper >/dev/null; then
        groupadd -r zookeeper
    fi

    # create kafka user
    if ! getent passwd zookeeper >/dev/null; then
        useradd -r -g zookeeper -d /usr/local/kafka \
            -s /bin/false -c "Zookeeper service user" zookeeper
    fi
}

chown_kafka_dirs() {
    chown kafka:kafka /etc/kafka
    chown kafka:kafka /var/log/kafka
    chown -R kafka:kafka /var/run/kafka
    chown -R kafka:kafka /usr/local/kafka
}

chown_zookeeper_scripts() {
    chown zookeeper:zookeeper /usr/local/kafka/bin/zookeeper-server-start.sh
    chown zookeeper:zookeeper /usr/local/kafka/bin/zookeeper-server-stop.sh
    chown zookeeper:zookeeper /usr/local/kafka/bin/zookeeper-shell.sh
}

case "$1" in
    configure)
        create_kafka_user_group
        chown_kafka_dirs
        create_zookeeper_user_group
        chown_zookeeper_scripts
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
